[package]
name = "aura"
version = "4.0.0-rc1"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"

[dependencies]
alpm = "1.1"
aura-arch = { path = "../aura-arch" }
aura-core = { path = "../aura-core" }
chrono = "0.4"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
colored = "2.0"
curl = "0.4"
i18n-embed = { version = "0.9.4", features = ["fluent-system"] }
i18n-embed-fl = "0.2"
itertools = "0.9"
log = "0.4"
pacmanconf = "0.1"
pbr = "1.0"
rayon = "1.5"
rust-embed = "5.6"
rustyline = "6.3"
simplelog = "0.8"
sudo = "0.5"
ubyte = "0.10"
unic-langid = { version = "0.9", features = ["macros"] }
webbrowser = "0.5"

[dependencies.linya]
version = "0.1"
git = "https://github.com/fosskers/linya"
rev = "6a28de0dbc641d7104ab4a7632a9fcb79f0762f1"

[features]
git = ["alpm/git"]
