[package]
name = "raur-curl"
version = "0.1.0"
edition = "2021"

[dependencies]
curl = "0.4.36"
raur = { version = "5.0.1", default-features = false, features = ["blocking-trait"] }
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.64"
